first implementation of solver, modification of config file structure…
bgrochal/GeneticEdgeDetector pull request #11
Opened 2017-04-13 01:28 UTC by jakud

…, implementation of factory classes for mutation. crossover and selection

2017-04-18 11:56 UTC, bgrochal requested changes
Great job, there are a few minor things to improve before merge. Really appreciate new config file structure and the config reader.

2017-04-18 11:56 UTC, bgrochal commented on .gitignore
> +/GeneticEdgeDetector.iml
The `*.iml` pattern has been already added to master, so we don't need this one right now.

2017-04-18 11:56 UTC, bgrochal commented on edgedetector/data/image_writer.py
> +                if mask[x][y] > 1e-01:  #todo is this threshold needed ?
Maybe use the [`math.isclose`](https://docs.python.org/3/whatsnew/3.5.html#pep-485-a-function-for-testing-approximate-equality) function? But is is possible for `mask` to have other values than 0 or 1?

2017-04-18 11:56 UTC, bgrochal commented on edgedetector/genetic_edge_detector.py
> +    print("Initialized in {:.2f} s".format(mid - start))
Probably this one will always return 0 seconds. Shouldn't we take more accurate unit?

2017-04-18 11:56 UTC, bgrochal commented on edgedetector/solver/crossover/crossover_factory.py
> +        if class_ == "RandomCrossover":
How about using some python-equivalent of [reflection](http://stackoverflow.com/questions/452969/does-python-have-an-equivalent-to-java-class-forname)?

2017-04-18 11:56 UTC, bgrochal commented on edgedetector/solver/evaluator/cost/overall_cost_evaluator.py
> +        cost_evaluators = [
It may be simplified to `self.cost_evaluators = [ ... ]` (and it is necessary then to remove line 22).

2017-04-18 11:56 UTC, bgrochal commented on test/solver/evaluator/fitness/fitness_evaluator_test.py
> +        self.\
Probably a typo, this new line is not needed.

2017-04-18 11:56 UTC, bgrochal commented on resources/config/config.yml
> +    initialSize: 5
Originally it was 512, but it doesn't matter right now (size of the population depends on the image shape).

2017-04-18 11:56 UTC, bgrochal commented on edgedetector/solver/stopcondition/stop_condition.py
> +This class defines basic interface for running genetic algorith unil
Typo: unil -> until

2017-04-18 11:56 UTC, bgrochal commented on edgedetector/solver/stopcondition/stop_condition_factory.py
> +        max_steps = config['maxSteps']
This line probably should be placed inside the 'if' statement below, because number of steps is tightly coupled with `StepsNumberStopCondition`, not with a stop condition in general.

2017-04-18 11:56 UTC, bgrochal commented on edgedetector/solver/solver.py
> +    def __initialize_crossover(self):
This method might be moved over the `__initialize_mutation` method.

2017-04-18 11:56 UTC, bgrochal commented on edgedetector/solver/solver.py
> +        fitness = self.__count_fitness(worst_genotype)
This one may be simplified to `return self.__count_fitness(worst_genotype)`

2017-04-18 11:56 UTC, bgrochal commented on edgedetector/solver/solver.py
> +        #   self.selection.select(...)      # todo not implemented yet
Leave this one as is. I would like to suggest the following flow:
1. Merge of this pull request.
2. Merge of my pull request containing implementation of the selection mechanism.
3. Then, I will change this line with invocation of a method returning two mates (genotypes) selected for crossover.

2017-04-18 11:56 UTC, bgrochal commented on edgedetector/solver/solver.py
> +        # while not whole population is new # todo what condition ?
I think that the condition could be: while size of newly-generated population is not equal to size of current population.

2017-04-18 11:56 UTC, bgrochal commented on edgedetector/solver/solver.py
> +        #   self.crossover.cross(...)       # todo which genotypes should we cross ?
These two returned by invocation of the `self.selection.select(self.population)` method above.

2017-04-18 11:56 UTC, bgrochal commented on edgedetector/solver/solver.py
> +        #   self.mutation.mutate(...)       # todo which genotypes should we mutate ?
According to the article: 

> Crossover and mutation operators are applied to the selected mates, and offsprings are generated.

However applying mutation to mates is not clear for me, too. From biological point of view, we should perform mutation on two offsprings generated as a result of performing crossover operation.

2017-04-18 12:03 UTC, bgrochal commented on edgedetector/solver/solver.py
> +        # while not whole population is new # todo what condition ?
By the way, I have forgotten about the following: we should replace current population with newly-generated one somewhere at the end of the iteration. Is there a piece of code performing this replacement?

2017-04-24 20:46 UTC, jakud commented on edgedetector/genetic_edge_detector.py
> +    print("Initialized in {:.2f} s".format(mid - start))
it's not meant for serious measurements. I added it just for my information

2017-04-24 21:01 UTC, jakud commented on edgedetector/solver/crossover/crossover_factory.py
> +        if class_ == "RandomCrossover":
We would have to pass full path to module in which the class to be instantiated is implemented or move subclasses of given abstract class to one module. In my opinion current solution is more readable

2017-04-24 21:07 UTC, jakud commented on edgedetector/data/image_writer.py
> +                if mask[x][y] > 1e-01:  #todo is this threshold needed ?
it should stay as it was before

2017-04-24 22:49 UTC, jakud commented on edgedetector/solver/solver.py
> +        # while not whole population is new # todo what condition ?
no, there is not. I think we should implement it after merging this PR and https://github.com/bgrochal/GeneticEdgeDetector/pull/12

2017-04-25 16:03 UTC, bgrochal approved these changes

2017-04-25 16:04 UTC, merged